Fixed icon
hYdos/Blaze4D pull request #8
Opened 2021-07-05 23:37 UTC by gudenau

2021-07-05 23:40 UTC, hYdos requested changes
maybe make the background transparent?

2021-07-06 00:01 UTC, gudenau commented
I don't know how that would work with different mods and such, does it work correctly?

2021-07-06 01:28 UTC, hYdos commented
> I don't know how that would work with different mods and such, does it work correctly?

 from what i have seen it works fine in other mods

2021-07-06 01:28 UTC, hYdos approved these changes

2021-07-06 01:28 UTC, merged